kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-problem-detector-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: node-problem-detector-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: node-problem-detector-cluster-role
  apiGroup: rbac.authorization.k8s.io